import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{ts,tsx}', './.storybook/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'fvs-black':   'var(--fvs-black)',
        'fvs-ink':     'var(--fvs-ink)',
        'fvs-graphite':'var(--fvs-graphite)',
        'fvs-slate':   'var(--fvs-slate)',
        'fvs-steel':   'var(--fvs-steel)',
        'fvs-fog':     'var(--fvs-fog)',
        'fvs-bone':    'var(--fvs-bone)',
        'fvs-paper':   'var(--fvs-paper)',
        'fvs-white':   'var(--fvs-white)',
        'fvs-amber':   'var(--fvs-amber)',
        'fvs-amber-dim':'var(--fvs-amber-dim)',
        'fvs-green':   'var(--fvs-green)',
        'fvs-red':     'var(--fvs-red)',
        'fvs-blue':    'var(--fvs-blue)',
        bg:            'var(--bg)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-inset':    'var(--bg-inset)',
        fg:            'var(--fg)',
        'fg-muted':    'var(--fg-muted)',
        'fg-subtle':   'var(--fg-subtle)',
        'fg-inverse':  'var(--fg-inverse)',
        accent:        'var(--accent)',
        nominal:       'var(--nominal)',
        alert:         'var(--alert)',
        info:          'var(--info)',
        line:          'var(--line)',
        'line-strong': 'var(--line-strong)',
      },
      fontFamily: {
        sans:    'var(--font-sans)',
        mono:    'var(--font-mono)',
        serif:   'var(--font-serif)',
        display: 'var(--font-display)',
      },
      fontSize: {
        micro:    'var(--t-micro)',
        tiny:     'var(--t-tiny)',
        small:    'var(--t-small)',
        body:     'var(--t-body)',
        'body-lg':'var(--t-body-lg)',
        h4:       'var(--t-h4)',
        h3:       'var(--t-h3)',
        h2:       'var(--t-h2)',
        h1:       'var(--t-h1)',
        display:  'var(--t-display)',
        hero:     'var(--t-hero)',
      },
      spacing: {
        's-0':  'var(--s-0)',
        's-1':  'var(--s-1)',
        's-2':  'var(--s-2)',
        's-3':  'var(--s-3)',
        's-4':  'var(--s-4)',
        's-5':  'var(--s-5)',
        's-6':  'var(--s-6)',
        's-7':  'var(--s-7)',
        's-8':  'var(--s-8)',
        's-9':  'var(--s-9)',
        's-10': 'var(--s-10)',
        's-11': 'var(--s-11)',
        's-12': 'var(--s-12)',
        'ct-gap-dense': 'var(--fvs-control-tile-gap-dense)',
        'ct-gap-default': 'var(--fvs-control-tile-gap-default)',
        'ct-gap-loose': 'var(--fvs-control-tile-gap-loose)',
        'ct-pad-default': 'var(--fvs-control-tile-padding-default)',
        'ct-pad-roomy': 'var(--fvs-control-tile-padding-roomy)',
        'ct-min-h': 'var(--fvs-control-tile-min-h)',
      },
      borderRadius: {
        'r-0':   'var(--r-0)',
        'r-1':   'var(--r-1)',
        'r-2':   'var(--r-2)',
        'r-3':   'var(--r-3)',
        'r-4':   'var(--r-4)',
        'r-pill':'var(--r-pill)',
      },
      boxShadow: {
        'shadow-1':       'var(--shadow-1)',
        'shadow-2':       'var(--shadow-2)',
        'shadow-3':       'var(--shadow-3)',
        'shadow-inset':   'var(--shadow-inset)',
        'shadow-console': 'var(--shadow-console)',
        'shadow-hair':    'var(--shadow-hair)',
      },
      transitionDuration: {
        fast: 'var(--dur-fast)',
        med:  'var(--dur-med)',
        slow: 'var(--dur-slow)',
      },
      transitionTimingFunction: {
        std: 'var(--ease-std)',
        'in':  'var(--ease-in)',
        out: 'var(--ease-out)',
      },
    },
  },
  plugins: [],
} satisfies Config;
